"use client";
import { useState } from "react";
import { Analysis, AttentionItem } from "@/app/data/types";
import { ArrowRight, MoreHorizontal, Sparkles } from "lucide-react";

const tabs=['Overview','Specification','Product Match','Siemens Lens','Vendor Fingerprint','Critical Clauses','Amendments','Evidence'];
const typeLabel:Record<AttentionItem['type'],string>={manual_review:'Manual Review',template_carryover:'Template',vendor_signal:'Vendor Signal',contradiction:'Çelişki',duplicate:'Tekrar',ambiguity:'Belirsizlik'};
export function AnalysisOverview({analysis}:{analysis:Analysis}){const [tab,setTab]=useState('Overview');const [aiOpen,setAiOpen]=useState(false);return <div className="mx-auto max-w-[1250px] px-8 py-7"><header className="flex items-start justify-between pb-5"><div><h1 className="text-[23px] font-extrabold tracking-[-.8px]">{analysis.title}</h1><p className="mt-1 text-xs text-[#667085]">{analysis.classification.systemClass} · {analysis.pageCount} sayfa · {analysis.documentDate}</p></div><div className="flex gap-2"><button onClick={()=>setAiOpen(true)} className="rounded-lg bg-[#17191c] px-3 py-2 text-xs font-bold text-white">Ask AI</button><button className="rounded-lg border border-[#e6e8ec] bg-white px-3 py-2 text-xs font-bold">Export</button><button className="rounded-lg border border-[#e6e8ec] bg-white px-2"><MoreHorizontal size={16}/></button></div></header><nav className="flex gap-6 overflow-auto border-b border-[#e6e8ec]">{tabs.map(item=><button onClick={()=>setTab(item)} key={item} className={`whitespace-nowrap border-b-2 py-3 text-xs font-bold ${tab===item?'border-[#173d83] text-[#173d83]':'border-transparent text-[#667085]'}`}>{item}</button>)}</nav>{tab==='Overview'?<Overview analysis={analysis}/>:<Placeholder tab={tab}/>}<AiDrawer open={aiOpen} close={()=>setAiOpen(false)} title={analysis.title}/></div>}
function Overview({analysis}:{analysis:Analysis}){const m=analysis.metrics;return <div className="pt-3"><div className="grid grid-cols-[1fr_220px] gap-2"><section className="panel p-4"><p className="eyebrow">Algılanan Sistem</p><div className="mt-1 flex items-center gap-2"><h2 className="text-sm font-extrabold">{analysis.classification.modality}</h2><span className="rounded bg-[#e9f7f1] px-1.5 py-1 text-[9px] font-bold text-[#137c5b]">Yüksek Güven</span></div><p className="mt-1 max-w-3xl text-[11px] leading-4 text-[#667085]">{analysis.classification.summary}</p><section className="mt-3 grid grid-cols-3 gap-2"><Decision label="Segment" value={analysis.classification.segment ?? '—'} detail={analysis.classification.systemClass}/><Decision label="Siemens Adayı" value="Analiz ediliyor" detail="—"/><Decision label="Teknik Uyum" value="—" detail="—"/></section></section><section className="panel h-fit"><PanelTitle title="Analiz Durumu"/><Metrics metrics={m}/></section></div><div className="mt-3 grid grid-cols-[1.05fr_1.05fr_1fr] gap-2"><section className="panel overflow-hidden"><PanelTitle title="Sistem Mimarisi"/>{analysis.architecture.map(item=><div className="grid grid-cols-[76px_1fr] border-t border-[#eef0f3] px-3 py-1.5 text-[9px]" key={item.category}><b>{item.label}</b><span className="text-[#667085]">{item.value}</span></div>)}</section><section className="panel overflow-hidden"><PanelTitle title="Teknik Bölümler" detail="Tümünü Gör →"/>{analysis.sections.map(item=><button key={item.id} className="flex w-full items-center justify-between border-t border-[#eef0f3] px-3 py-1.5 text-left text-[9px] hover:bg-[#fafbfc]"><span>{item.sourceLabel}</span><span className="font-bold">{item.requirementCount ?? '—'}</span></button>)}</section><section className="panel overflow-hidden"><PanelTitle title="Dikkat Gerektiren Noktalar" detail="Tümünü Gör →"/>{analysis.attentionItems.map(item=><div key={item.id} className="grid grid-cols-[34px_1fr] gap-2 border-t border-[#eef0f3] px-3 py-2 text-[9px]"><b className="text-[#e24b4b]">{item.sourceClause}</b><div><div className="flex justify-between gap-1"><b>{item.title}</b><span className="status h-fit bg-[#f0ecff] px-1 py-0.5 text-[8px] text-[#6c4cb5]">{typeLabel[item.type]}</span></div><p className="mt-1 leading-3 text-[#667085]">{item.description}</p></div></div>)}</section></div></div>}
function Decision({label,value,detail}:{label:string;value:string;detail:string}){return <div className="rounded-md border border-[#e6e8ec] bg-[#fbfcfe] p-2"><p className="text-[8px] font-bold uppercase tracking-wide text-[#667085]">{label}</p><b className="mt-1 block text-[10px]">{value}</b><p className="mt-0.5 text-[8px] text-[#667085]">{detail}</p></div>}
function PanelTitle({title,detail}:{title:string;detail?:string}){return <div className="flex items-center justify-between px-3 py-2.5"><h3 className="text-[11px] font-bold">{title}</h3>{detail&&<span className="text-[9px] text-[#173d83]">{detail}</span>}</div>}
function Metrics({metrics}:{metrics:Analysis['metrics']}){return <div className="divide-y divide-[#e6e8ec]">{[['Teknik Gereksinim',metrics.technicalRequirements],['Kritik Çakışma',metrics.criticalConflicts],['Manuel Review',metrics.manualReviews],['Anomali',metrics.anomalies]].map(([label,value])=><div className="flex justify-between px-3 py-2 text-[10px]" key={String(label)}><span className="text-[#667085]">{label}</span><b>{value}</b></div>)}</div>}
function relevance(value:string){return ({very_high:'Çok Yüksek',high:'Yüksek',medium:'Orta',low:'Düşük',none:'—'} as Record<string,string>)[value]}
function Placeholder({tab}:{tab:string}){return <div className="panel mt-6 p-8"><p className="eyebrow">{tab}</p><h2 className="mt-2 text-lg font-bold">Bu görünüm hazırlanıyor</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#667085]">Arayüz sözleşmesi hazır. Bu alan, backend pipeline&apos;ından gelen yapılandırılmış sonuçları gösterecek.</p></div>}
function AiDrawer({open,close,title}:{open:boolean;close:()=>void;title:string}){return <aside className={`fixed inset-y-0 right-0 z-20 w-[390px] border-l border-[#e6e8ec] bg-white p-6 shadow-[-10px_0_35px_rgba(23,25,28,.1)] transition-transform ${open?'translate-x-0':'translate-x-full'}`}><div className="flex items-center justify-between"><div><h2 className="text-base font-bold">Tender AI</h2><p className="mt-1 text-xs text-[#667085]">Bu şartname hakkında sorun.</p></div><button onClick={close} className="text-lg text-[#667085]">×</button></div><div className="mt-7 space-y-2">{['Bu şartnamenin teknik özetini çıkar.','En ayırt edici 5 teknik madde hangileri?','Vendor fingerprint’i ne belirliyor?','Siemens için problemli maddeleri göster.'].map(prompt=><button key={prompt} className="flex w-full items-start gap-2 rounded-md border border-[#e6e8ec] p-3 text-left text-xs font-medium hover:bg-[#fafbfc]"><Sparkles size={14} className="shrink-0 text-[#173d83]"/>{prompt}</button>)}</div><div className="absolute inset-x-6 bottom-6 rounded-md border border-[#e6e8ec] p-3 text-xs text-[#98a2b3]">{title} hakkında sorun…</div></aside>}
