create extension if not exists pgcrypto;

create table if not exists products (id uuid primary key default gen_random_uuid(), product_code text unique not null, manufacturer text not null, product_name text not null, modality text not null, system_class text not null, active boolean not null default true, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists parameter_definitions (id uuid primary key default gen_random_uuid(), canonical_key text unique not null, label_tr text not null, category text not null, value_type text not null check (value_type in ('NUMBER','BOOLEAN','ENUM','TEXT','RANGE')), unit text, is_core boolean not null default false, tender_relevance text not null, notes text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists parameter_aliases (id uuid primary key default gen_random_uuid(), parameter_definition_id uuid not null references parameter_definitions(id) on delete cascade, alias text not null, normalized_alias text not null, created_at timestamptz not null default now(), unique(parameter_definition_id, normalized_alias));
create table if not exists product_parameter_values (id uuid primary key default gen_random_uuid(), product_id uuid not null references products(id), parameter_definition_id uuid not null references parameter_definitions(id), numeric_value numeric, boolean_value boolean, text_value text, enum_value text, range_min numeric, range_max numeric, knowledge_status text not null default 'UNKNOWN' check (knowledge_status in ('PM_VERIFIED','USER_VERIFIED','AI_INFERRED','UNKNOWN')), updated_at timestamptz not null default now(), unique(product_id, parameter_definition_id));
create table if not exists import_runs (id uuid primary key default gen_random_uuid(), source_filename text not null, status text not null, product_count integer not null default 0, parameter_count integer not null default 0, value_count integer not null default 0, warning_count integer not null default 0, error_count integer not null default 0, summary jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists products_modality_system_class_idx on products(modality, system_class);
create index if not exists parameter_definitions_category_idx on parameter_definitions(category);
create index if not exists product_parameter_values_product_idx on product_parameter_values(product_id);
